-- Shivam Kirana Store: order line-items setup
-- Run this once in the Supabase SQL Editor.

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null,
  product_id text,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  line_total numeric(12,2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists order_items_order_id_idx on public.order_items(order_id);
alter table public.order_items enable row level security;

drop policy if exists order_items_insert_checkout on public.order_items;
create policy order_items_insert_checkout on public.order_items
for insert to anon, authenticated
with check (exists (select 1 from public.orders o where o.id::text = order_id));

drop policy if exists order_items_shopkeeper_select on public.order_items;
create policy order_items_shopkeeper_select on public.order_items
for select to authenticated
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'shopkeeper'));